### ISSUE TITLE
Modify inside bounds function parameters to take only bounds

### ISSUE THREAD

**Issue by wehard** [wehard/rt#12]
https://github.com/wehard/rt/blob/94621193d047d90c4320d5550c166e65fdd1cfae/src/octree/octree.c#L18

This could be a function that only takes bounds a and b. Better to make it more generic so it could be used for all bounds.

**Comment by wehard** [comment]
Also move the function to bounds.c if norme permits. Which it does as there is no bounds.c yet. 😋

**Comment by rasmusjaa** [comment]
Handled this in my last pull request.
#14
